### PR TITLE
Created Baby Yoda cowfile.

### PR DESCRIPTION
**Pull request by RandoNandoz**
After learning how to use GIMP instead of Photoshop and using the ~~magnetic lasso~~ "intelligent scissors" feature, I created a transparent picture of Baby Yoda, without a background.

I then put the image through the cowsay file generator - and voila!

### CODE REVIEW

**Comment by RandoNandoz** [comment]
I have merged the wrong repos...

**Comment by paulkaefer** [comment]
yeah, I'm not sure what you did, @RandoNandoz... can you open a new PR?

**Comment by RandoNandoz** [comment]
@paulkaefer Do you want me to merge from master to master, or from experimental-cows to experimental-cows?

**Comment by paulkaefer** [comment]
@RandoNandoz yeah master's good

**Pull request closed without merging**
