### PR TITLE
Added the Baby Yoda cowfile.

### PR DESCRIPTION
**Pull request by RandoNandoz**
Correction for PR: #27

### CODE REVIEW

**Comment by paulkaefer** [comment]
The colors look a bit off...

Screen Shot 2020-10-02 at 08 25 16

**Comment by RandoNandoz** [comment]
Fixed the weird colours.

**Comment by RandoNandoz** [comment]
Screenshot_20201003_104808
It works!

**Review by paulkaefer — APPROVED** [review]

**Comment by paulkaefer** [comment]
While it doesn't look good on my Terminal, it's neat via your screenshot. Thanks, @RandoNandoz!

**Pull request merged**
