### PR TITLE
Adding tons more cows, cleaning up and adding sources to existing ones. Fixing examples.md for color cows.

### PR DESCRIPTION
**Pull request by charc0al**
- Added a ton of new cows
- Added author/source links to all pixel art cows
- Touched up / remastered almost all the existing ones so they are all top quality
- Updated the make-examples.sh script to look for matching PNG files when generating examples so a link to the source image can be inserted rather than printing all those color codes.
- Added 24-bit true color support to the cowsay file converter

### CODE REVIEW

**Comment by paulkaefer** [comment]
Thanks for the PR. Wow. I'd like to spend more time reviewing, since there are quite a few files here.

Initial thoughts:
* nice work updating the converter & .cowrc
* can we think of a way so folks without true color terminals won't get all the cows by default? perhaps an optional COWS list in .cowrc that contains only the ASCII cows? unless you can think of a better way. we might want a separate folder, for organization.

**Comment by charc0al** [comment]
Yeah I was thinking about possibly separating them into their own folders, I'd be fine with that. It's worth noting that the vast majority of the cows only require the standard 8-bit color supported by most terminals. Only a few of the cows require true color, and maybe we could just put them in a 'true-color' directory? The regular color ones could also go in a 'color' directory too if you'd prefer they be separated. I saw you mentioned in another comment that you prefer the ASCII cows so I would be fine with moving them into a sub-directory.

Also, the COWS list in the .cowrc file was just meant as an example, not to contain all cows. You are welcome to update it to contain just the ASCII cows on your repo if you like. Or if you'd prefer I updated it as part of this PR I can, just let me know. Thanks.

**Comment by paulkaefer** [comment]
A `true-color` directory sounds great.

Sure, if it's no trouble, how about making an `ASCII_COWS` variable within .cowrc & then a user can decide whether to use `${COWS}` or `${ASCII_COWS}`. And yes, `COWS` as simply an example is great.

**Comment by charc0al** [comment]
Just added another commit that changes randomsay / COWS variable to use only ASCII cows by default. Separate list and command for pixelsay / PIXEL_COWS. Will move true color cows into their own directory in a bit.

**Comment by charc0al** [comment]
True color cows have now been moved to 'true-color' directory, make-examples.sh has been updated accordingly and now true color cows will appear at the end of the examples list.

**Comment by paulkaefer** [comment]
I can't say I've reviewed these all, but anyway thanks a ton for the contributions!

**Pull request merged**
